list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/bar_b/bar_b_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/bar/bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/button_subtle/button_subtle_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/card/card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/checkbox/checkbox_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/container/container_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/dropdown/dropdown_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/image/image_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/label/label_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/panel/panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/qrcode/qrcode_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/slider/slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/base/switch/switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/button_danger/button_danger_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/button_icon/button_icon_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/button_primary/button_primary_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/card_bay/card_bay_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/card_supercharge/card_supercharge_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/card_tariff/card_tariff_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/chip_card/chip_card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/chip_header/chip_header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/code_qr/code_qr_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control_checkbox/control_checkbox_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control_slider/control_slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/control_switch/control_switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/derived/tile_2/tile_2_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/derived/tile/tile_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/field_dropdown/field_dropdown_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/field_slider/field_slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_back/icon_back_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_close/icon_close_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_diagnostic/icon_diagnostic_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_nfc/icon_nfc_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_plug/icon_plug_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_settings/icon_settings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_supercharge_green/icon_supercharge_green_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_supercharge/icon_supercharge_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_zap/icon_zap_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/nav_header/nav_header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/preferences_modal/preferences_modal_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/progress/progress_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/qr_code/qr_code_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/row_supercharge/row_supercharge_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/row_tariff/row_tariff_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/row_toggle/row_toggle_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/tile_stat/tile_stat_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_bold_132_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_bold_168_95999145507812_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_11_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_13_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_14_079999923706055_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_15_359999656677246_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_15_360000610351562_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_15_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_16_64000129699707_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_16_639999389648438_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_19_19999885559082_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_19_200000762939453_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_21_29920196533203_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_21_299203872680664_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_44_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_medium_56_31999969482422_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_11_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_13_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_14_079999923706055_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_15_359999656677246_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_15_360000610351562_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_15_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_16_64000129699707_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_16_639999389648438_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_19_19999885559082_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_19_200000762939453_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_24_57600212097168_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_regular_24_576000213623047_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_15_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_18_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_19_19999885559082_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_19_200000762939453_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_22_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_23_03999900817871_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_23_040000915527344_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_24_57600212097168_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_24_576000213623047_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_24_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_25_599998474121094_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_26_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_28_15999984741211_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_28_160001754760742_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_30_719999313354492_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_32_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_33_28000259399414_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_33_279998779296875_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_34_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_36_0447998046875_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_36_044803619384766_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_40_96000289916992_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_40_959999084472656_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_43_52000045776367_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_gabarito_semibold_43_52000427246094_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_bold_11_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_bold_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_bold_46_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_bold_86_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_medium_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_medium_15_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_regular_12_5_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_regular_15_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_regular_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_semi_bold_10_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_semi_bold_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_semi_bold_13_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_semi_bold_15_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_semi_bold_21_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_semi_bold_30_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_semi_bold_38_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_inter_semi_bold_41_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_back_byd_425x149_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_back_byd_755x265_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_back_byd_1039x365_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_front_byd_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_back_323661_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_close_30435_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_diagnostic_323653_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_nfc_19919_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_plug_19916_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_settings_1988_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_supercharge_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_supercharge_green_24419_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_icon_zap_19913_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_lucide_nfc_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_plug_large_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_qr_receipt_64x64_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_qr_receipt_115x115_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_263_32_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_263_263_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_270_4_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_270_5_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_270_6_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_270_7_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_270_8_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_273_184_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_273_185_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_273_186_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/image_vec_328_444_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_wheel_base_98_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_wheel_base_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_wheel_rim_98_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_wheel_rim_data.c
  ${CMAKE_CURRENT_LIST_DIR}/lvpower_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/lvpower.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/auth_guest_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/auth_member_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/bay_overview_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/charging_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/complete_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/diagnostics_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/idle_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/station_settings_gen.c)